type: "transformation"
version: "1.0"
pipeline:
  components:
    BOOKS1:
      type: "table-input"
      parameters:
        componentName: "BOOKS1"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "BOOKS1"
        columnNames:
        - "ID"
        - "NAME"
        - "CATEGORY"
        - "PRICE"
        timeOffset:
    BOOKS1 2:
      type: "table-input"
      parameters:
        componentName: "BOOKS1 2"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "BOOKS2"
        columnNames:
        - "ID"
        - "NAME"
        - "CATEGORY"
        - "PRICE"
        timeOffset:
    Except:
      type: "except"
      sources:
      - "BOOKS1"
      - "BOOKS1 2"
      parameters:
        componentName: "Except"
        castTypes: "Yes"
        primaryTable: "BOOKS1"
    Intersect:
      type: "intersect"
      sources:
      - "BOOKS1"
      - "BOOKS1 2"
      parameters:
        componentName: "Intersect"
        castTypes: "Yes"
    Unite:
      type: "unite"
      sources:
      - "BOOKS1"
      - "BOOKS1 2"
      parameters:
        componentName: "Unite"
        method: "All Columns"
        castTypes: "Yes"
        addSourceComponentColumn: "No"
        removeDuplicates: "Yes"
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "Except"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "Except_book1vsBook2"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Rewrite Table 2:
      type: "rewrite-table"
      sources:
      - "Intersect"
      parameters:
        componentName: "Rewrite Table 2"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "intersect_Book1VsBook2"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Rewrite Table 3:
      type: "rewrite-table"
      sources:
      - "Unite"
      parameters:
        componentName: "Rewrite Table 3"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "Unite_Book1Book2"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    BOOKS1:
      position:
        x: -260
        "y": -40
      tempMetlId: 1
    BOOKS1 2:
      position:
        x: -270
        "y": 70
      tempMetlId: 2
    Except:
      position:
        x: -10
        "y": -40
      tempMetlId: 3
    Intersect:
      position:
        x: 0
        "y": 40
      tempMetlId: 4
    Unite:
      position:
        x: 10
        "y": 130
      tempMetlId: 5
    Rewrite Table:
      position:
        x: 150
        "y": -40
      tempMetlId: 6
    Rewrite Table 2:
      position:
        x: 150
        "y": 40
      tempMetlId: 7
    Rewrite Table 3:
      position:
        x: 150
        "y": 130
      tempMetlId: 8
